apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- deployment.yaml
- service.yaml
images:
- name: goserver
  newName: deividroger/gitopsfc
  newTag: 5117e572d500ff717ea9813a6c80b79b57bb4c87
kind: Kustomization
