apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- deployment.yaml
- service.yaml
images:
- name: goserver
  newName: deividroger/gitopsfc
  newTag: 0bedbf9e86a49fcc385ece3345d2282ca6321da4
kind: Kustomization
