apiVersion: v1
kind: Service
metadata:
  name: goserver-service
  namespace: default
spec:
  selector:
    app: goserver-service
  ports:
  - name: goserver-service
    protocol: TCP
    port: 8080
    targetPort: 8080
